trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: FlutterInstall@0
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'
    flutterDirectory: '.'

- task: FlutterTest@0
  inputs:
    projectDirectory: '.'
    testName: 'test'
    testPlainName: 'test01'


